"use client";
import Head from "next/head";
import {
  Container,
  Heading,
  Spinner,
  Table,
  Tbody,
  Td,
  Th,
  Thead,
  Tr,
} from "@chakra-ui/react";
import { useProductsQueries } from "@/features/products/UseProducts";
import Image from "next/image";

// chakra ui
// form formik handle form
// yup validation form
// axios api call
// react-query manager API call (caching, state...) Tanstack query

export default function Home() {
  const { data: products, isLoading } = useProductsQueries();
  // send data to table for UI
  const renderProduct = () => {
    return products?.map((product) => {
      return (
        <Tr key={product.id}>
          <Td>{product.id}</Td>
          <Td>{product.name}</Td>
          <Td>{product.price}</Td>
          <Td>{product.description}</Td>
          <Td>
            <Image
              src={product.image}
              alt={`Image of ${product.name}`}
              width={250}
              height={250}
            />
          </Td>
        </Tr>
      );
    });
  };

  return (
    <>
      <Head>
        <title>Data Fetching</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Heading>Page Products</Heading>
          <Table>
            <Thead>
              <Tr>
                <Th>ID</Th>
                <Th>Name</Th>
                <Th>Price</Th>
                <Th>Description</Th>
                <Th>Image</Th>
              </Tr>
            </Thead>
            <Tbody>
              {/* <Tr>
                <Td>Contoh</Td>
                <Td>Contoh</Td>
                <Td>Contoh</Td>
                <Td>Contoh</Td>
                <Td>Contoh</Td>
              </Tr> */}
              {renderProduct()}
              {isLoading ? <Spinner /> : null}
              {/* {isLoading && <Spinner /> : null} */}
            </Tbody>
          </Table>
        </Container>
      </main>
    </>
  );
}
